# Includes all common properties irrespective of any environment
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
---
management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
    httptrace:
      enabled: true
  trace:
    http:
      include:
        - REQUEST_HEADERS
        - RESPONSE_HEADERS
        - COOKIE_HEADERS
        - REMOTE_ADDRESS
  endpoints:
    web:
      exposure:
        include: "*"
---
#i18n settings start here
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

supportedLocales:
  - en_US
  - es
  - fr
#i18n settings end here
---
petstore-api:
  pet:
    findByStatus: https://petstore.swagger.io/v2/pet/findByStatus